projects:
  ucenter:
    schema: "packages/api/script/__generated__/ucenter.graphql"
    documents:
      - "src/services/ucenter/**/*.ts"
      - "packages/org/src/**/*.ts"
      - "packages/layout/src/**/*.ts"
      - "packages/api/script/__generated__/ucenter.graphql"
    extensions:
      endpoints:
        default:
          url: ${GQLGEN_UCENTER_ENDPOINT}
          headers:
            Authorization: bearer ${GQLGEN_TOKEN}
            X-Tenant-ID: ${GQLGEN_TENANT_ID}
