projects:
  ucenter:
    schema: "packages/api/script/generated/ucenter.graphql"
    documents:
      - "packages/api/script/generated/ucenter.graphql"
      - "packages/org/src/**/*.ts"
      - "packages/layout/src/**/*.ts"
  msgcenter:
    schema: "packages/api/script/generated/msgcenter.graphql"
    documents:
      - "packages/api/script/generated/msgcenter.graphql"
      - "packages/layout/src/**/*.ts"
  test:
    schema: "https://trygql.formidable.dev/graphql/basic-pokedex"
    documents:
      - "examples/with-urql/src/**/*.tsx"
      - "examples/with-urql/src/**/*.ts"
